// Gerado automaticamente por build.py — não edite à mão.
const CATALOG_DATA = {
  "motherboards": [
    {
      "Código": "MB-001",
      "Fabricante": "ASUS",
      "Modelo": "P4S800D-X",
      "Identificação/Revisão": "—",
      "Formato": "ATX",
      "Socket": "Socket 478",
      "Chipset principal": "SiS 648FX",
      "Southbridge": "SiS 964",
      "Memória suportada": "DDR",
      "Slots de memória": "4 DIMM",
      "Vídeo/expansão principal": "AGP 8x",
      "Outros slots": "5 PCI",
      "Armazenamento": "IDE/SATA",
      "CPU instalada": "Não confirmado",
      "RAM instalada": "Não confirmado",
      "BIOS": "Não confirmado",
      "Data BIOS": "Não confirmado",
      "Sistema testado": "Não confirmado",
      "Estado": "Não testada",
      "Detalhamento técnico / observações": "Fotos físicas: anexos 1–3; chipset SiS 964 visível no anexo 2.",
      "Fonte": "Anexos 1–3"
    },
    {
      "Código": "MB-002",
      "Fabricante": "ECS",
      "Modelo": "G41T-M7 V1.0",
      "Identificação/Revisão": "1ª unidade",
      "Formato": "microATX",
      "Socket": "LGA775",
      "Chipset principal": "Intel G41",
      "Southbridge": "ICH7",
      "Memória suportada": "DDR3",
      "Slots de memória": "2 DIMM",
      "Vídeo/expansão principal": "PCIe x16",
      "Outros slots": "PCI/PCIe",
      "Armazenamento": "SATA",
      "CPU instalada": "Intel Core 2 Duo E8400",
      "RAM instalada": "4 GB DDR3",
      "BIOS": "Não confirmado",
      "Data BIOS": "Não confirmado",
      "Sistema testado": "Não confirmado",
      "Estado": "Funcionando",
      "Detalhamento técnico / observações": "Cadastro anterior do projeto; fotos/HWiNFO detalhado não aparecem no documento recebido.",
      "Fonte": "Cadastro anterior"
    },
    {
      "Código": "MB-003",
      "Fabricante": "ECS",
      "Modelo": "G41T-M7 V1.0",
      "Identificação/Revisão": "2ª unidade",
      "Formato": "microATX",
      "Socket": "LGA775",
      "Chipset principal": "Intel G41",
      "Southbridge": "ICH7",
      "Memória suportada": "DDR3",
      "Slots de memória": "2 DIMM",
      "Vídeo/expansão principal": "PCIe x16",
      "Outros slots": "PCI/PCIe",
      "Armazenamento": "SATA",
      "CPU instalada": "Não confirmado",
      "RAM instalada": "Não confirmado",
      "BIOS": "Não confirmado",
      "Data BIOS": "Não confirmado",
      "Sistema testado": "Não confirmado",
      "Estado": "Liga, sem vídeo",
      "Detalhamento técnico / observações": "Segunda unidade física; não deve ser confundida com a MB-002.",
      "Fonte": "Cadastro anterior"
    },
    {
      "Código": "MB-004",
      "Fabricante": "Dell",
      "Modelo": "OptiPlex 380",
      "Identificação/Revisão": "DP/N 0HN7XN",
      "Formato": "Proprietário Dell",
      "Socket": "LGA775",
      "Chipset principal": "Intel G41 (Eaglelake)",
      "Southbridge": "ICH7",
      "Memória suportada": "DDR3",
      "Slots de memória": "2 DIMM",
      "Vídeo/expansão principal": "PCIe 2.0 x16",
      "Outros slots": "2 PCI + PCIe x1",
      "Armazenamento": "SATA",
      "CPU instalada": "Intel Core 2 Duo E7500",
      "RAM instalada": "4 GB DDR3 dual-channel",
      "BIOS": "A05",
      "Data BIOS": "24/02/2011",
      "Sistema testado": "Windows 11 Enterprise x64 22H2, build 22621.1483",
      "Estado": "Funcionando",
      "Detalhamento técnico / observações": "HWiNFO: CPU E7500, 45 nm, stepping R0, Wolfdale-M, SSPEC SLGTE, 2c/2t, 2,93 GHz, L2 3 MB, TDP 65 W. Memória Micron 8JTF25664AZ-1G4D1, 2 GB por módulo, DDR3-1332/PC3-10700, 1,50 V. GPU integrada Intel GMA 4500.",
      "Fonte": "Anexos 4–8 e 9–14"
    },
    {
      "Código": "MB-005",
      "Fabricante": "Lenovo",
      "Modelo": "L-A780 Rev.1 / M2RS780MH",
      "Identificação/Revisão": "Rev.1",
      "Formato": "microATX",
      "Socket": "AM2/AM2+",
      "Chipset principal": "AMD RS780",
      "Southbridge": "SB700",
      "Memória suportada": "DDR2",
      "Slots de memória": "Não confirmado",
      "Vídeo/expansão principal": "PCIe x16",
      "Outros slots": "PCI/PCIe",
      "Armazenamento": "SATA",
      "CPU instalada": "Não confirmado",
      "RAM instalada": "Não confirmado",
      "BIOS": "Não confirmado",
      "Data BIOS": "Não confirmado",
      "Sistema testado": "Não confirmado",
      "Estado": "Não testada",
      "Detalhamento técnico / observações": "Cadastro anterior do projeto; sem HWiNFO identificável no documento recebido.",
      "Fonte": "Cadastro anterior"
    },
    {
      "Código": "MB-006",
      "Fabricante": "ACC",
      "Modelo": "ACC1800N-2C1P",
      "Identificação/Revisão": "—",
      "Formato": "Mini-ITX",
      "Socket": "BGA integrado",
      "Chipset principal": "Intel Bay Trail-D",
      "Southbridge": "Integrado",
      "Memória suportada": "DDR3L",
      "Slots de memória": "Não confirmado",
      "Vídeo/expansão principal": "PCIe/mini PCIe conforme placa",
      "Outros slots": "Não confirmado",
      "Armazenamento": "SATA",
      "CPU instalada": "Intel Celeron J1800",
      "RAM instalada": "4 GB Kingston DDR3L",
      "BIOS": "F2 AZ",
      "Data BIOS": "06/03/2015",
      "Sistema testado": "Windows 10 Enterprise",
      "Estado": "Funcionando",
      "Detalhamento técnico / observações": "Cadastro anterior do projeto; CPU integrada à placa.",
      "Fonte": "Cadastro anterior"
    },
    {
      "Código": "MB-007",
      "Fabricante": "CCE",
      "Modelo": "NM70-I V1.0",
      "Identificação/Revisão": "V1.0",
      "Formato": "Mini-ITX",
      "Socket": "BGA integrado",
      "Chipset principal": "Intel NM70",
      "Southbridge": "Integrado",
      "Memória suportada": "DDR3L",
      "Slots de memória": "Não confirmado",
      "Vídeo/expansão principal": "PCIe conforme placa",
      "Outros slots": "Não confirmado",
      "Armazenamento": "SATA",
      "CPU instalada": "Intel Celeron 847",
      "RAM instalada": "4 GB Kingston DDR3L",
      "BIOS": "UEFI",
      "Data BIOS": "30/11/2012",
      "Sistema testado": "Windows 10 Enterprise",
      "Estado": "Funcionando",
      "Detalhamento técnico / observações": "Cadastro anterior do projeto; CPU integrada à placa.",
      "Fonte": "Cadastro anterior"
    },
    {
      "Código": "MB-008",
      "Fabricante": "Dell",
      "Modelo": "OptiPlex 745",
      "Identificação/Revisão": "0KT234 A01 / PCB DP/N UX762",
      "Formato": "Proprietário Dell",
      "Socket": "LGA775",
      "Chipset principal": "Intel Q965 (Broadwater-GC) rev. C1",
      "Southbridge": "ICH8/R rev. B0",
      "Memória suportada": "DDR2",
      "Slots de memória": "4 DIMM",
      "Vídeo/expansão principal": "PCIe 1.0 x16",
      "Outros slots": "2 PCI + PCIe",
      "Armazenamento": "SATA",
      "CPU instalada": "Intel Pentium Dual-Core E2160",
      "RAM instalada": "2 GB DDR2",
      "BIOS": "2.3.1",
      "Data BIOS": "21/05/2007",
      "Sistema testado": "Windows 10 Enterprise x64, build 19041.4713",
      "Estado": "Funcionando",
      "Detalhamento técnico / observações": "CPU E2160: Conroe-1M, stepping M0, SSPEC SLA8Z, 65 nm, 2c/2t, 1,80 GHz, FSB 800, L2 1 MB, TDP 65 W. RAM: Samsung M3 78T2953EZ3-CE6 1 GB PC2-5300 + Smart Modular SG564288FG8N6KF-Z1 1 GB PC2-6400. Vídeo integrado Intel GMA 3000. Placa física também mostra DP/N BR-0CT103-48105-76G-0770 Rev. A04 em outra etiqueta; manter ambas as identificações até reconciliação física.",
      "Fonte": "Anexos 15–30"
    }
  ],
  "gpus": [
    {
      "Código": "VG-001",
      "Fabricante da placa": "XFX Pine Group Inc.",
      "Modelo": "GeForce 7300 LE",
      "Fabricante GPU": "NVIDIA",
      "Codinome": "G72",
      "Revisão": "B1 / chipset A1",
      "Litografia": "90 nm",
      "Interface": "PCIe 1.1 x16 (2,5 GT/s), operando x16",
      "Memória": "256 MB",
      "Tipo memória": "DDR2 SDRAM",
      "Barramento memória": "64-bit",
      "Clock GPU": "199,3 MHz",
      "Clock memória": "168,8 MHz (337,5 MHz efetivos)",
      "ROPs": "4",
      "TMUs": "—",
      "Shaders": "3 vertex shaders",
      "ReBAR": "Não suportado",
      "PCI ID": "PCIVEN_10DE&DEV_01D1",
      "Saídas": "VGA + DVI (conforme cadastro/fotos anteriores)",
      "Tipo": "Discreta",
      "Estado": "Funcionando / detectada",
      "Observações": "Testada no Dell OptiPlex 745 com Windows 10 Enterprise; fabricante da placa XFX.",
      "Fonte": "Anexos 31–33"
    },
    {
      "Código": "VG-002",
      "Fabricante da placa": "XFX Pine Group Inc.",
      "Modelo": "Radeon HD 4350",
      "Fabricante GPU": "AMD/ATI",
      "Codinome": "RV710 / Luigi",
      "Revisão": "—",
      "Litografia": "55 nm",
      "Interface": "PCIe 2.0 x16 (5,0 GT/s), operando x16 a 2,5 GT/s",
      "Memória": "1 GB",
      "Tipo memória": "DDR2 SDRAM (Samsung indicado parcialmente)",
      "Barramento memória": "64-bit",
      "Clock GPU": "599,1 MHz",
      "Clock memória": "396,0 MHz (792,0 MHz efetivos)",
      "ROPs": "2",
      "TMUs": "8",
      "Shaders": "80 unified shaders",
      "ReBAR": "Não suportado",
      "PCI ID": "PCIVEN_1002&DEV_954F",
      "Saídas": "VGA + DVI (conforme cadastro/fotos anteriores)",
      "Tipo": "Discreta",
      "Estado": "Funcionando / detectada",
      "Observações": "VBIOS 011.021.000.007.000000; testada no Windows 10 Enterprise.",
      "Fonte": "Anexos 34–36"
    }
  ],
  "cpus": [
    {
      "Código": "CPU-001",
      "Fabricante": "Intel",
      "Modelo": "Core 2 Duo E7500",
      "Codinome": "Wolfdale-M",
      "Socket": "LGA775",
      "Litografia": "45 nm",
      "Stepping": "R0",
      "SSPEC": "SLGTE",
      "Núcleos": "2",
      "Threads": "2",
      "Clock base": "2,93 GHz",
      "FSB/Barramento": "266,7 MHz",
      "Multiplicador": "x11",
      "Cache L2": "3 MB",
      "TDP": "65 W",
      "Instruções/recursos observados": "EM64T, EIST, MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, DEP, VMX",
      "Placa associada": "MB-004",
      "Estado": "Funcionando"
    },
    {
      "Código": "CPU-002",
      "Fabricante": "Intel",
      "Modelo": "Pentium Dual-Core E2160",
      "Codinome": "Conroe-1M",
      "Socket": "LGA775",
      "Litografia": "65 nm",
      "Stepping": "M0",
      "SSPEC": "SLA8Z",
      "Núcleos": "2",
      "Threads": "2",
      "Clock base": "1,80 GHz",
      "FSB/Barramento": "200 MHz",
      "Multiplicador": "x9",
      "Cache L2": "1 MB",
      "TDP": "65 W",
      "Instruções/recursos observados": "EM64T, EIST, MMX, SSE, SSE2, SSE3, SSSE3, DEP",
      "Placa associada": "MB-008",
      "Estado": "Funcionando"
    },
    {
      "Código": "CPU-003",
      "Fabricante": "Intel",
      "Modelo": "Core 2 Duo E8400",
      "Codinome": "Wolfdale",
      "Socket": "LGA775",
      "Litografia": "45 nm",
      "Stepping": "Não confirmado",
      "SSPEC": "Não confirmado",
      "Núcleos": "2",
      "Threads": "2",
      "Clock base": "3,00 GHz",
      "FSB/Barramento": "333 MHz",
      "Multiplicador": "x9",
      "Cache L2": "6 MB",
      "TDP": "65 W",
      "Instruções/recursos observados": "Não confirmado",
      "Placa associada": "MB-002",
      "Estado": "Funcionando"
    },
    {
      "Código": "CPU-004",
      "Fabricante": "Intel",
      "Modelo": "Celeron J1800",
      "Codinome": "Bay Trail-D",
      "Socket": "BGA",
      "Litografia": "22 nm",
      "Stepping": "Não confirmado",
      "SSPEC": "Não confirmado",
      "Núcleos": "2",
      "Threads": "2",
      "Clock base": "2,41 GHz base",
      "FSB/Barramento": "Não aplicável",
      "Multiplicador": "Não confirmado",
      "Cache L2": "1 MB",
      "TDP": "10 W",
      "Instruções/recursos observados": "Não confirmado",
      "Placa associada": "MB-006",
      "Estado": "Funcionando"
    },
    {
      "Código": "CPU-005",
      "Fabricante": "Intel",
      "Modelo": "Celeron 847",
      "Codinome": "Sandy Bridge",
      "Socket": "BGA",
      "Litografia": "32 nm",
      "Stepping": "Não confirmado",
      "SSPEC": "Não confirmado",
      "Núcleos": "2",
      "Threads": "2",
      "Clock base": "1,10 GHz",
      "FSB/Barramento": "Não aplicável",
      "Multiplicador": "Não confirmado",
      "Cache L2": "2 MB",
      "TDP": "17 W",
      "Instruções/recursos observados": "Não confirmado",
      "Placa associada": "MB-007",
      "Estado": "Funcionando"
    }
  ],
  "memory": [
    {
      "Código": "RAM-001",
      "Fabricante": "Micron",
      "Part number": "8JTF25664AZ-1G4D1",
      "Capacidade": "2 GB",
      "Tipo": "DDR3 UDIMM",
      "Classificação": "PC3-10700 / DDR3-1332",
      "Clock nominal": "667 MHz",
      "Tensão": "1,50 V",
      "ECC": "Não",
      "Ranks": "Não confirmado",
      "Placa associada": "MB-004",
      "Observações/SPD": "Módulo 1; timings JEDEC visíveis: 666,7 MHz 9-9-9-24; 533,3 MHz 7-7-7-20; 400 MHz 6-6-6-15; 333,3 MHz 5-5-5-12."
    },
    {
      "Código": "RAM-002",
      "Fabricante": "Micron",
      "Part number": "8JTF25664AZ-1G4D1",
      "Capacidade": "2 GB",
      "Tipo": "DDR3 UDIMM",
      "Classificação": "PC3-10700 / DDR3-1332",
      "Clock nominal": "667 MHz",
      "Tensão": "1,50 V",
      "ECC": "Não",
      "Ranks": "Não confirmado",
      "Placa associada": "MB-004",
      "Observações/SPD": "Módulo 2; sistema em dual-channel, total 4 GB."
    },
    {
      "Código": "RAM-003",
      "Fabricante": "Samsung",
      "Part number": "M3 78T2953EZ3-CE6",
      "Capacidade": "1 GB",
      "Tipo": "DDR2 UDIMM",
      "Classificação": "PC2-5300",
      "Clock nominal": "333 MHz",
      "Tensão": "1,80 V",
      "ECC": "Não",
      "Ranks": "2 ranks",
      "Placa associada": "MB-008",
      "Observações/SPD": "Semana/ano 08/08; serial 18013508; JEDEC 200/266/333 MHz, CL 3/4/5."
    },
    {
      "Código": "RAM-004",
      "Fabricante": "Smart Modular",
      "Part number": "SG564288FG8N6KF-Z1",
      "Capacidade": "1 GB",
      "Tipo": "DDR2 UDIMM",
      "Classificação": "PC2-6400",
      "Clock nominal": "400 MHz",
      "Tensão": "1,80 V",
      "ECC": "Não",
      "Ranks": "1 rank",
      "Placa associada": "MB-008",
      "Observações/SPD": "SPD mostra JEDEC 266/333/400 MHz, CL 4/5/6; serial FFFFFFFF; campo semana/ano inválido 165/165."
    },
    {
      "Código": "RAM-005",
      "Fabricante": "Kingston",
      "Part number": "Não confirmado",
      "Capacidade": "4 GB",
      "Tipo": "DDR3",
      "Classificação": "Não confirmado",
      "Clock nominal": "Não confirmado",
      "Tensão": "Não confirmado",
      "ECC": "Não confirmado",
      "Ranks": "Não confirmado",
      "Placa associada": "MB-002",
      "Observações/SPD": "Cadastro anterior do projeto."
    },
    {
      "Código": "RAM-006",
      "Fabricante": "Kingston",
      "Part number": "Não confirmado",
      "Capacidade": "4 GB",
      "Tipo": "DDR3L",
      "Classificação": "Não confirmado",
      "Clock nominal": "Não confirmado",
      "Tensão": "Não confirmado",
      "ECC": "Não confirmado",
      "Ranks": "Não confirmado",
      "Placa associada": "MB-006",
      "Observações/SPD": "Cadastro anterior do projeto."
    },
    {
      "Código": "RAM-007",
      "Fabricante": "Kingston",
      "Part number": "Não confirmado",
      "Capacidade": "4 GB",
      "Tipo": "DDR3L",
      "Classificação": "Não confirmado",
      "Clock nominal": "Não confirmado",
      "Tensão": "Não confirmado",
      "ECC": "Não confirmado",
      "Ranks": "Não confirmado",
      "Placa associada": "MB-007",
      "Observações/SPD": "Cadastro anterior do projeto."
    }
  ],
  "tests": [
    {
      "Código do teste": "TEST-001",
      "Item": "MB-004",
      "Tipo de teste": "Teste funcional com HWiNFO 64 v8.46-5960",
      "Condição/cenário": "Inicialização e identificação completa",
      "Resultado": "Aprovado",
      "Sistema/ambiente": "Windows 11 Enterprise x64 22H2",
      "Conclusão": "CPU, chipset, memória e vídeo integrado reconhecidos.",
      "Fonte": "Anexos 4–8"
    },
    {
      "Código do teste": "TEST-002",
      "Item": "MB-008",
      "Tipo de teste": "Teste funcional com HWiNFO 64 v8.46-5960 e CPU-Z 2.19.0 x64",
      "Condição/cenário": "Inicialização e identificação completa",
      "Resultado": "Aprovado",
      "Sistema/ambiente": "Windows 10 Enterprise x64",
      "Conclusão": "CPU, chipset, BIOS, memória e vídeo integrado reconhecidos.",
      "Fonte": "Anexos 23–30"
    },
    {
      "Código do teste": "TEST-003",
      "Item": "VG-001",
      "Tipo de teste": "Teste de detecção da GPU",
      "Condição/cenário": "Instalada no MB-008 / OptiPlex 745",
      "Resultado": "Aprovado",
      "Sistema/ambiente": "Windows 10 Enterprise x64",
      "Conclusão": "GeForce 7300 LE detectada em PCIe x16; clocks e memória reconhecidos.",
      "Fonte": "Anexos 31–33"
    },
    {
      "Código do teste": "TEST-004",
      "Item": "VG-002",
      "Tipo de teste": "Teste de detecção da GPU",
      "Condição/cenário": "Instalada em plataforma Windows 10",
      "Resultado": "Aprovado",
      "Sistema/ambiente": "Windows 10 Enterprise x64",
      "Conclusão": "Radeon HD 4350 detectada; VBIOS, clocks, barramento e shaders reconhecidos.",
      "Fonte": "Anexos 34–36"
    },
    {
      "Código do teste": "TEST-005",
      "Item": "MB-003",
      "Tipo de teste": "Teste de energização",
      "Condição/cenário": "Placa liga, porém não apresenta vídeo",
      "Resultado": "Pendente diagnóstico",
      "Sistema/ambiente": "Não informado",
      "Conclusão": "Requer inspeção de RAM, CPU, BIOS, capacitores, alimentação e vídeo.",
      "Fonte": "Cadastro anterior"
    }
  ],
  "photoIndex": [
    {
      "Referência": "Anexos 1–3",
      "Item": "MB-001",
      "Equipamento": "ASUS P4S800D-X",
      "Conteúdo das imagens": "Vista geral, slots, chipset SiS 964 e layout físico."
    },
    {
      "Referência": "Anexos 4–8",
      "Item": "MB-004",
      "Equipamento": "Dell OptiPlex 380",
      "Conteúdo das imagens": "HWiNFO: CPU, placa-mãe, memória, GPU integrada e sistema operacional."
    },
    {
      "Referência": "Anexos 9–14",
      "Item": "MB-004",
      "Equipamento": "Dell OptiPlex 380",
      "Conteúdo das imagens": "Fotos físicas, etiquetas, PCB, conectores e identificação DP/N 0HN7XN."
    },
    {
      "Referência": "Anexos 15–22",
      "Item": "MB-008",
      "Equipamento": "Dell OptiPlex 745",
      "Conteúdo das imagens": "Fotos físicas, etiquetas, chipset NVIDIA auxiliar, socket, Super I/O e PCB DP/N UX762."
    },
    {
      "Referência": "Anexos 23–30",
      "Item": "MB-008",
      "Equipamento": "Dell OptiPlex 745",
      "Conteúdo das imagens": "HWiNFO/CPU-Z: CPU, chipset, BIOS, RAM, SPD e vídeo integrado."
    },
    {
      "Referência": "Anexos 31–33",
      "Item": "VG-001",
      "Equipamento": "XFX GeForce 7300 LE",
      "Conteúdo das imagens": "CPU-Z/HWiNFO com identificação, clocks, barramento, memória e PCI ID."
    },
    {
      "Referência": "Anexos 34–36",
      "Item": "VG-002",
      "Equipamento": "XFX Radeon HD 4350",
      "Conteúdo das imagens": "HWiNFO/CPU-Z com VBIOS, clocks, shaders, memória e PCI ID."
    }
  ],
  "equipment": [
    {
      "Código": "MB-001",
      "Categoria": "Placa-mãe",
      "Fabricante": "ASUS",
      "Modelo": "P4S800D-X",
      "Plataforma": "Socket 478 / SiS 648FX",
      "CPU/GPU principal": "Não confirmado",
      "Memória": "Não confirmado",
      "Estado": "Não testada",
      "Fonte": "Anexos 1–3",
      "Observações": "Fotos físicas: anexos 1–3; chipset SiS 964 visível no anexo 2."
    },
    {
      "Código": "MB-002",
      "Categoria": "Placa-mãe",
      "Fabricante": "ECS",
      "Modelo": "G41T-M7 V1.0",
      "Plataforma": "LGA775 / Intel G41",
      "CPU/GPU principal": "Intel Core 2 Duo E8400",
      "Memória": "4 GB DDR3",
      "Estado": "Funcionando",
      "Fonte": "Cadastro anterior",
      "Observações": "Cadastro anterior do projeto; fotos/HWiNFO detalhado não aparecem no documento recebido."
    },
    {
      "Código": "MB-003",
      "Categoria": "Placa-mãe",
      "Fabricante": "ECS",
      "Modelo": "G41T-M7 V1.0",
      "Plataforma": "LGA775 / Intel G41",
      "CPU/GPU principal": "Não confirmado",
      "Memória": "Não confirmado",
      "Estado": "Liga, sem vídeo",
      "Fonte": "Cadastro anterior",
      "Observações": "Segunda unidade física; não deve ser confundida com a MB-002."
    },
    {
      "Código": "MB-004",
      "Categoria": "Placa-mãe",
      "Fabricante": "Dell",
      "Modelo": "OptiPlex 380",
      "Plataforma": "LGA775 / Intel G41 (Eaglelake)",
      "CPU/GPU principal": "Intel Core 2 Duo E7500",
      "Memória": "4 GB DDR3 dual-channel",
      "Estado": "Funcionando",
      "Fonte": "Anexos 4–8 e 9–14",
      "Observações": "HWiNFO: CPU E7500, 45 nm, stepping R0, Wolfdale-M, SSPEC SLGTE, 2c/2t, 2,93 GHz, L2 3 MB, TDP 65 W. Memória Micron 8JTF25664AZ-1G4D1, 2 GB por módulo, DDR3-1332/PC3-10700, 1,50 V. GPU integrada Intel GMA 4500."
    },
    {
      "Código": "MB-005",
      "Categoria": "Placa-mãe",
      "Fabricante": "Lenovo",
      "Modelo": "L-A780 Rev.1 / M2RS780MH",
      "Plataforma": "AM2/AM2+ / AMD RS780",
      "CPU/GPU principal": "Não confirmado",
      "Memória": "Não confirmado",
      "Estado": "Não testada",
      "Fonte": "Cadastro anterior",
      "Observações": "Cadastro anterior do projeto; sem HWiNFO identificável no documento recebido."
    },
    {
      "Código": "MB-006",
      "Categoria": "Placa-mãe",
      "Fabricante": "ACC",
      "Modelo": "ACC1800N-2C1P",
      "Plataforma": "BGA integrado / Intel Bay Trail-D",
      "CPU/GPU principal": "Intel Celeron J1800",
      "Memória": "4 GB Kingston DDR3L",
      "Estado": "Funcionando",
      "Fonte": "Cadastro anterior",
      "Observações": "Cadastro anterior do projeto; CPU integrada à placa."
    },
    {
      "Código": "MB-007",
      "Categoria": "Placa-mãe",
      "Fabricante": "CCE",
      "Modelo": "NM70-I V1.0",
      "Plataforma": "BGA integrado / Intel NM70",
      "CPU/GPU principal": "Intel Celeron 847",
      "Memória": "4 GB Kingston DDR3L",
      "Estado": "Funcionando",
      "Fonte": "Cadastro anterior",
      "Observações": "Cadastro anterior do projeto; CPU integrada à placa."
    },
    {
      "Código": "MB-008",
      "Categoria": "Placa-mãe",
      "Fabricante": "Dell",
      "Modelo": "OptiPlex 745",
      "Plataforma": "LGA775 / Intel Q965 (Broadwater-GC) rev. C1",
      "CPU/GPU principal": "Intel Pentium Dual-Core E2160",
      "Memória": "2 GB DDR2",
      "Estado": "Funcionando",
      "Fonte": "Anexos 15–30",
      "Observações": "CPU E2160: Conroe-1M, stepping M0, SSPEC SLA8Z, 65 nm, 2c/2t, 1,80 GHz, FSB 800, L2 1 MB, TDP 65 W. RAM: Samsung M3 78T2953EZ3-CE6 1 GB PC2-5300 + Smart Modular SG564288FG8N6KF-Z1 1 GB PC2-6400. Vídeo integrado Intel GMA 3000. Placa física também mostra DP/N BR-0CT103-48105-76G-0770 Rev. A04 em outra etiqueta; manter ambas as identificações até reconciliação física."
    },
    {
      "Código": "VG-001",
      "Categoria": "Placa de vídeo",
      "Fabricante": "XFX Pine Group Inc.",
      "Modelo": "GeForce 7300 LE",
      "Plataforma": "PCIe 1.1 x16 (2,5 GT/s), operando x16",
      "CPU/GPU principal": "NVIDIA G72",
      "Memória": "256 MB DDR2 SDRAM",
      "Estado": "Funcionando / detectada",
      "Fonte": "Anexos 31–33",
      "Observações": "Testada no Dell OptiPlex 745 com Windows 10 Enterprise; fabricante da placa XFX."
    },
    {
      "Código": "VG-002",
      "Categoria": "Placa de vídeo",
      "Fabricante": "XFX Pine Group Inc.",
      "Modelo": "Radeon HD 4350",
      "Plataforma": "PCIe 2.0 x16 (5,0 GT/s), operando x16 a 2,5 GT/s",
      "CPU/GPU principal": "AMD/ATI RV710 / Luigi",
      "Memória": "1 GB DDR2 SDRAM (Samsung indicado parcialmente)",
      "Estado": "Funcionando / detectada",
      "Fonte": "Anexos 34–36",
      "Observações": "VBIOS 011.021.000.007.000000; testada no Windows 10 Enterprise."
    }
  ],
  "guide": [
    {
      "Categoria": "Placa-mãe",
      "Prefixo": "MB",
      "Exemplo": "MB-009",
      "Quando criar novo código": "Cada unidade física recebe código próprio, mesmo sendo modelo repetido.",
      "Campos mínimos": "Fabricante, modelo, revisão, estado, fotos.",
      "Observação": "Nunca reutilizar código de item baixado."
    },
    {
      "Categoria": "Placa de vídeo",
      "Prefixo": "VG",
      "Exemplo": "VG-003",
      "Quando criar novo código": "Cada placa física recebe código próprio.",
      "Campos mínimos": "Modelo, GPU, interface, memória, estado.",
      "Observação": "Registrar perfil e saídas quando visíveis."
    },
    {
      "Categoria": "Processador",
      "Prefixo": "CPU",
      "Exemplo": "CPU-006",
      "Quando criar novo código": "Quando o processador puder ser identificado individualmente.",
      "Campos mínimos": "Modelo, socket/BGA, clock, placa associada.",
      "Observação": "CPU soldada pode permanecer associada à placa."
    },
    {
      "Categoria": "Memória",
      "Prefixo": "RAM",
      "Exemplo": "RAM-008",
      "Quando criar novo código": "Cada módulo físico deve receber código próprio.",
      "Campos mínimos": "Fabricante, capacidade, tipo, frequência, placa associada.",
      "Observação": "Usar part number e serial quando disponíveis."
    },
    {
      "Categoria": "Teste",
      "Prefixo": "TEST",
      "Exemplo": "TEST-006",
      "Quando criar novo código": "Cada sessão de diagnóstico ou validação relevante.",
      "Campos mínimos": "Item, data, cenário, resultado e conclusão.",
      "Observação": "Não sobrescrever testes anteriores."
    },
    {
      "Categoria": "Estado",
      "Prefixo": "",
      "Exemplo": "",
      "Quando criar novo código": "Valores padronizados",
      "Campos mínimos": "Funcionando; Liga, sem vídeo; Não testada; Em diagnóstico; Necessita reparo; Baixada.",
      "Observação": "Selecionar pelas listas suspensas."
    },
    {
      "Categoria": "Fonte de evidência",
      "Prefixo": "",
      "Exemplo": "",
      "Quando criar novo código": "Indicar anexos, software ou cadastro anterior.",
      "Campos mínimos": "Ex.: Anexos 31–33; HWiNFO; CPU-Z.",
      "Observação": "Campos não comprovados devem ficar como “Não confirmado”."
    },
    {
      "Categoria": "Fotos",
      "Prefixo": "",
      "Exemplo": "",
      "Quando criar novo código": "Registrar referência de anexos ou caminho futuro.",
      "Campos mínimos": "Frente, verso, etiquetas, tela do HWiNFO/CPU-Z.",
      "Observação": "O índice de fotos liga cada imagem ao item."
    },
    {
      "Categoria": "Aquisição",
      "Prefixo": "",
      "Exemplo": "",
      "Quando criar novo código": "Preencher quando conhecido.",
      "Campos mínimos": "Data, procedência, valor pago e localização física.",
      "Observação": "Esses campos podem ser adicionados em versão futura sem alterar códigos."
    }
  ],
  "meta": {
    "counts": {
      "motherboards": 8,
      "gpus": 2,
      "cpus": 5,
      "memory": 7
    }
  }
};
