// Catalogo unificado de conteudos. Itens que apareciam em mais de uma secao
// do site classico agora possuem varias categorias e sao exibidos uma unica vez.

const cta = {
  labs: { pt: 'Acessar laboratórios', en: 'Open labs', es: 'Acceder a laboratorios' },
  github: { pt: 'Abrir no GitHub', en: 'Open on GitHub', es: 'Abrir en GitHub' },
  repo: { pt: 'Abrir repositório', en: 'Open repository', es: 'Abrir repositorio' },
  course: { pt: 'Acessar curso', en: 'Open course', es: 'Acceder al curso' },
  plan: { pt: 'Acessar plano', en: 'Access plan', es: 'Acceder al plan' },
  guide: { pt: 'Acessar guia', en: 'Access guide', es: 'Acceder a la guía' },
  read: { pt: 'Ler material', en: 'Read material', es: 'Leer material' },
  sim: { pt: 'Abrir simulador', en: 'Open simulator', es: 'Abrir simulador' },
};

const unbGrad = {
  pt: 'Graduação em Engenharia de Redes de Comunicação',
  en: 'Undergraduate Program in Communication Network Engineering',
  es: 'Carrera de Ingeniería de Redes de Comunicación',
};

const certMeta = { pt: 'Certificação profissional', en: 'Professional certification', es: 'Certificación profesional' };

export const CATEGORY_ORDER = ['labs', 'courses', 'disciplines', 'simulators'];

export const resources = [
  {
    id: 'labs-80211',
    featured: true,
    categories: ['labs'],
    href: '/labs/index.html',
    cta: cta.labs,
    title: { pt: 'Série Prática de Segurança 802.11 & Pentest', en: '802.11 Security & Pentest Practical Series', es: 'Serie Práctica de Seguridad 802.11 y Pentest' },
    text: {
      pt: 'Cinco roteiros práticos completos: Reconhecimento Passivo (Kismet), Captura & Análise (Wireshark), Protocolos WPA2/WPA3, Ataques Deauth/Rogue AP e Arsenal de Ferramentas.',
      en: 'Five complete hands-on guides: Passive Reconnaissance (Kismet), Capture & Analysis (Wireshark), WPA2/WPA3 Protocols, Deauth/Rogue AP Attacks, and Tool Arsenal.',
      es: 'Cinco guías prácticas completas: Reconocimiento Pasivo (Kismet), Captura y Análisis (Wireshark), Protocolos WPA2/WPA3, Ataques Deauth/Rogue AP y Arsenal de Herramientas.',
    },
    tags: ['Wi-Fi Pentest', 'Kismet', 'WPA3'],
  },
  {
    id: 'lab-wireshark',
    categories: ['labs'],
    href: 'https://github.com/peotta/lab-wireshark-unb/tree/main',
    external: true,
    cta: cta.github,
    title: { pt: 'Laboratório de Análise de Tráfego com Wireshark', en: 'Traffic Analysis Lab with Wireshark', es: 'Laboratorio de Análisis de Tráfico con Wireshark' },
    text: {
      pt: 'Roteiros práticos e capturas de pacotes para dissecação de protocolos TCP/IP, DNS, HTTP/HTTPS, Telnet/SSH, análise do handshake triplo e diagnóstico de redes na Universidade de Brasília.',
      en: 'Hands-on guides and packet captures to dissect TCP/IP, DNS, HTTP/HTTPS, and Telnet/SSH, analyze the three-way handshake, and troubleshoot networks at the University of Brasília.',
      es: 'Guías prácticas y capturas de paquetes para diseccionar TCP/IP, DNS, HTTP/HTTPS y Telnet/SSH, analizar el three-way handshake y diagnosticar redes en la Universidad de Brasilia.',
    },
    tags: ['Wireshark', 'TCP/IP', 'UnB'],
  },
  {
    id: 'lab-kali-docker',
    categories: ['labs'],
    href: 'https://github.com/peotta/lab-kali-docker',
    external: true,
    cta: cta.github,
    title: { pt: 'Laboratório Kali Linux em Contêiner Docker', en: 'Kali Linux Lab in a Docker Container', es: 'Laboratorio Kali Linux en Contenedor Docker' },
    text: {
      pt: 'Ambiente de segurança ofensiva e testes de penetração leve, isolado e reprodutível baseado em contêineres Docker com Kali Linux, ideal para estudantes e práticas acadêmicas.',
      en: 'A lightweight, isolated, and reproducible offensive security and penetration testing environment based on Kali Linux Docker containers, ideal for students and academic practice.',
      es: 'Entorno de seguridad ofensiva y pruebas de penetración ligero, aislado y reproducible basado en contenedores Docker con Kali Linux, ideal para estudiantes y prácticas académicas.',
    },
    tags: ['Kali Linux', 'Docker', 'Pentest'],
  },
  {
    id: 'course-linux',
    featured: true,
    categories: ['courses'],
    href: '/guias/index-linux.html',
    cta: cta.course,
    title: { pt: 'Curso Linux para Engenheiros', en: 'Linux Course for Engineers', es: 'Curso Linux para Ingenieros' },
    text: {
      pt: 'Curso completo de Linux voltado para estudantes e profissionais de Engenharia de Redes, Ciência da Computação e Cibersegurança. Aborda fundamentos, administração, redes, automação, monitoramento, troubleshooting e segurança.',
      en: 'Complete Linux course for students and professionals in Network Engineering, Computer Science, and Cybersecurity. Covers fundamentals, administration, networking, automation, monitoring, troubleshooting, and security.',
      es: 'Curso completo de Linux para estudiantes y profesionales de Ingeniería de Redes, Ciencias de la Computación y Ciberseguridad. Aborda fundamentos, administración, redes, automatización, monitoreo, resolución de problemas y seguridad.',
    },
    tags: ['Linux', 'Shell', 'Online'],
  },
  {
    id: 'course-wifi',
    categories: ['courses', 'labs'],
    href: '/guias/wifi.html',
    cta: cta.course,
    title: { pt: 'Segurança em Redes Wi-Fi', en: 'Wi-Fi Network Security', es: 'Seguridad en Redes Wi-Fi' },
    text: {
      pt: 'Curso e material de aula sobre segurança em redes sem fio, com laboratórios práticos, fundamentos de IEEE 802.11, análise de riscos, hardening e auditoria autorizada.',
      en: 'Course and class material on wireless network security, with practical labs, IEEE 802.11 fundamentals, risk analysis, hardening, and authorized auditing.',
      es: 'Curso y material de clase sobre seguridad en redes inalámbricas, con laboratorios prácticos, fundamentos de IEEE 802.11, análisis de riesgos, hardening y auditoría autorizada.',
    },
    tags: ['IEEE 802.11', 'Hardening'],
  },
  {
    id: 'cert-ccna',
    categories: ['courses'],
    href: '/certificacoes/ccna.html',
    cta: cta.plan,
    meta: certMeta,
    title: { pt: 'Certificação CCNA Cisco 200-301', en: 'Cisco CCNA 200-301 Certification', es: 'Certificación Cisco CCNA 200-301' },
    text: {
      pt: 'Plano de estudos para preparação à certificação Cisco CCNA 200-301, com organização semanal, laboratórios, comandos e revisão.',
      en: 'Study plan for Cisco CCNA 200-301 certification preparation, including weekly organization, labs, commands, and review.',
      es: 'Plan de estudios para la preparación de la certificación Cisco CCNA 200-301, con organización semanal, laboratorios, comandos y revisión.',
    },
    tags: ['Cisco', '200-301'],
  },
  {
    id: 'cert-ccna-cyber',
    categories: ['courses'],
    href: '/certificacoes/ccna-cybersecurity.html',
    cta: cta.plan,
    meta: certMeta,
    title: { pt: 'Certificação CCNA Cybersecurity 200-201', en: 'CCNA Cybersecurity 200-201 Certification', es: 'Certificación CCNA Cybersecurity 200-201' },
    text: {
      pt: 'Plano de estudos com foco em operações de segurança, SOC, monitoramento, análise de hosts, intrusão em rede e resposta a incidentes.',
      en: 'Study plan focused on security operations, SOC, monitoring, host analysis, network intrusion analysis, and incident response.',
      es: 'Plan de estudios con foco en operaciones de seguridad, SOC, monitoreo, análisis de hosts, intrusión en red y respuesta a incidentes.',
    },
    tags: ['Cisco', 'SOC', '200-201'],
  },
  {
    id: 'cert-ccst',
    categories: ['courses'],
    href: '/certificacoes/ccst.html',
    cta: cta.plan,
    meta: certMeta,
    title: { pt: 'Certificação CCST Cybersecurity 100-160', en: 'CCST Cybersecurity 100-160 Certification', es: 'Certificación CCST Cybersecurity 100-160' },
    text: {
      pt: 'Plano de estudos para o Cisco Certified Support Technician Cybersecurity, com fundamentos de segurança, redes, endpoints, vulnerabilidades, risco e resposta a incidentes.',
      en: 'Study plan for the Cisco Certified Support Technician Cybersecurity, covering security fundamentals, networks, endpoints, vulnerabilities, risk, and incident response.',
      es: 'Plan de estudios para el Cisco Certified Support Technician Cybersecurity, con fundamentos de seguridad, redes, endpoints, vulnerabilidades, riesgo y respuesta a incidentes.',
    },
    tags: ['Cisco', '100-160'],
  },
  {
    id: 'cert-fortinet',
    categories: ['courses'],
    href: '/certificacoes/fortinet.html',
    cta: cta.guide,
    meta: certMeta,
    title: { pt: 'Certificação Fortinet NSE 1 a NSE 3', en: 'Fortinet NSE 1 to NSE 3 Certification', es: 'Certificación Fortinet NSE 1 a NSE 3' },
    text: {
      pt: 'Guia de estudos para a trilha Fortinet inicial, incluindo FCF, FCA, cadastro no portal, custos, tópicos cobrados e links oficiais.',
      en: 'Study guide for the initial Fortinet track, including FCF, FCA, portal registration, costs, exam topics, and official links.',
      es: 'Guía de estudios para la ruta inicial de Fortinet, incluyendo FCF, FCA, registro en el portal, costos, temas evaluados y enlaces oficiales.',
    },
    tags: ['Fortinet', 'NSE', 'FCF/FCA'],
  },
  {
    id: 'ene0011',
    code: 'ENE0011',
    unb: true,
    categories: ['disciplines'],
    href: 'https://github.com/peotta/labredes',
    external: true,
    cta: cta.repo,
    meta: unbGrad,
    title: { pt: 'Laboratório de Redes', en: 'Network Laboratory', es: 'Laboratorio de Redes' },
    text: {
      pt: 'Atividades experimentais com dispositivos de rede, análise de protocolos, VLANs e roteamento.',
      en: 'Experimental activities with network devices, protocol analysis, VLANs, and routing.',
      es: 'Actividades experimentales con dispositivos de red, análisis de protocolos, VLAN y enrutamiento.',
    },
    tags: ['VLAN', 'Roteamento'],
  },
  {
    id: 'ene0025',
    code: 'ENE0025',
    unb: true,
    categories: ['disciplines'],
    href: 'https://github.com/peotta/PTR',
    external: true,
    cta: cta.repo,
    meta: unbGrad,
    title: { pt: 'Protocolos de Transporte e Roteamento', en: 'Transport and Routing Protocols', es: 'Protocolos de Transporte y Enrutamiento' },
    text: {
      pt: 'Estudo da arquitetura TCP/IP, dos protocolos de transporte e dos fundamentos de roteamento.',
      en: 'Study of TCP/IP architecture, transport protocols, and routing fundamentals.',
      es: 'Estudio de la arquitectura TCP/IP, los protocolos de transporte y los fundamentos del enrutamiento.',
    },
    tags: ['TCP/IP', 'OSPF'],
  },
  {
    id: 'ene0021',
    code: 'ENE0021',
    unb: true,
    categories: ['disciplines'],
    href: 'https://github.com/peotta/topicos',
    external: true,
    cta: cta.repo,
    meta: unbGrad,
    title: { pt: 'Tópicos em Redes de Comunicação 3', en: 'Topics in Communication Networks 3', es: 'Temas en Redes de Comunicación 3' },
    text: {
      pt: 'Temas avançados em segurança de redes, criptografia, resposta a incidentes, forense digital, DevSecOps e automação.',
      en: 'Advanced topics in network security, cryptography, incident response, digital forensics, DevSecOps, and automation.',
      es: 'Temas avanzados en seguridad de redes, criptografía, respuesta a incidentes, forense digital, DevSecOps y automatización.',
    },
    tags: ['DevSecOps', 'Forense'],
  },
  {
    id: 'ene0274',
    code: 'ENE0274',
    unb: true,
    categories: ['disciplines'],
    href: 'https://github.com/peotta/topicos',
    external: true,
    cta: cta.repo,
    meta: unbGrad,
    title: { pt: 'Fundamentos de Redes', en: 'Network Fundamentals', es: 'Fundamentos de Redes' },
    text: {
      pt: 'Fundamentos conceituais sobre protocolos, serviços e arquitetura de redes de computadores.',
      en: 'Conceptual foundations of protocols, services, and computer network architecture.',
      es: 'Fundamentos conceptuales sobre protocolos, servicios y arquitectura de redes de computadoras.',
    },
    tags: ['Protocolos'],
  },
  {
    id: 'ene0358',
    code: 'ENE0358',
    unb: true,
    categories: ['disciplines'],
    href: '/guias/dicas.html',
    cta: cta.read,
    meta: unbGrad,
    title: {
      pt: 'Projeto Final de Graduação 1 e 2',
      en: 'Undergraduate Final Project 1 and 2',
      es: 'Proyecto Final de Grado 1 y 2',
    },
    text: {
      pt: 'ENE0358 (PFG 1) e ENE0360/ENE0458 (PFG 2): matrícula, avaliação, etapas do relatório, defesa e normas ABNT.',
      en: 'ENE0358 (PFG 1) and ENE0360/ENE0458 (PFG 2): enrollment, assessment, report stages, defense, and ABNT standards.',
      es: 'ENE0358 (PFG 1) y ENE0360/ENE0458 (PFG 2): matrícula, evaluación, etapas del informe, defensa y normas ABNT.',
    },
    tags: ['TCC', 'ABNT', 'ENE0360', 'ENE0458'],
  },
  {
    id: 'pga0009',
    code: 'PGA0009',
    unb: true,
    categories: ['disciplines'],
    href: 'https://github.com/peotta/PGA0009',
    external: true,
    cta: cta.repo,
    meta: {
      pt: 'MBA em Privacidade e Segurança da Informação (PGAP/FACE/UnB)',
      en: 'MBA in Privacy and Information Security (PGAP/FACE/UnB)',
      es: 'MBA en Privacidad y Seguridad de la Información (PGAP/FACE/UnB)',
    },
    title: { pt: 'Gestão de Operações de Segurança', en: 'Security Operations Management', es: 'Gestión de Operaciones de Seguridad' },
    text: {
      pt: 'Fundamentos de segurança da informação, gestão de identidade e acesso, criptografia, segurança em redes, IDS/IPS, monitoramento, SOC, backup e Security by Design.',
      en: 'Information security fundamentals, identity and access management, cryptography, network security, IDS/IPS, monitoring, SOC, backup, and Security by Design.',
      es: 'Fundamentos de seguridad de la información, gestión de identidad y acceso, criptografía, seguridad en redes, IDS/IPS, monitoreo, SOC, backup y Security by Design.',
    },
    tags: ['MBA', 'SOC', 'IAM'],
  },
  {
    id: 'ppee-orientacao',
    code: 'PPEE',
    unb: true,
    categories: ['disciplines'],
    href: '/orientacao/mestrado-ppee.html',
    cta: cta.guide,
    meta: {
      pt: 'Mestrado Profissional em Engenharia Elétrica (PPEE/UnB)',
      en: 'Professional Master’s in Electrical Engineering (PPEE/UnB)',
      es: 'Maestría Profesional en Ingeniería Eléctrica (PPEE/UnB)',
    },
    title: {
      pt: 'Orientação de Mestrado Profissional',
      en: 'Professional Master’s Supervision',
      es: 'Orientación de Maestría Profesional',
    },
    text: {
      pt: 'Guia para orientandos do PPEE: créditos, prazos, produção exigida para a defesa, etapas da dissertação e normas de redação.',
      en: 'Guide for PPEE advisees: credits, deadlines, publication required for the defense, thesis stages, and writing standards.',
      es: 'Guía para orientandos del PPEE: créditos, plazos, producción exigida para la defensa, etapas de la disertación y normas de redacción.',
    },
    tags: ['Mestrado', 'Dissertação', 'Segurança Cibernética'],
  },
  {
    id: 'ppee2017',
    code: 'PPEE2017',
    unb: true,
    categories: ['disciplines'],
    href: 'https://github.com/peotta/PPEE2017',
    external: true,
    cta: cta.repo,
    meta: {
      pt: 'Mestrado Profissional em Engenharia Elétrica (PPEE/UnB)',
      en: 'Professional Master’s in Electrical Engineering (PPEE/UnB)',
      es: 'Maestría Profesional en Ingeniería Eléctrica (PPEE/UnB)',
    },
    title: { pt: 'Tópicos em Segurança Cibernética 5', en: 'Topics in Cybersecurity 5', es: 'Temas en Ciberseguridad 5' },
    text: {
      pt: 'Tópicos avançados em cibercrime, guerra cibernética, fraudes digitais e Cyber Threat Intelligence (CTI), com estudos de caso e aprendizagem baseada em problemas.',
      en: 'Advanced topics in cybercrime, cyber warfare, digital fraud, and Cyber Threat Intelligence (CTI), with case studies and problem-based learning.',
      es: 'Temas avanzados en ciberdelito, guerra cibernética, fraudes digitales y Cyber Threat Intelligence (CTI), con estudios de caso y aprendizaje basado en problemas.',
    },
    tags: ['Mestrado', 'CTI', 'Cibercrime'],
  },
  {
    id: 'ppca0049',
    code: 'PPCA0049',
    unb: true,
    categories: ['disciplines'],
    href: 'https://github.com/peotta/PPCA0049',
    external: true,
    cta: cta.repo,
    meta: {
      pt: 'Doutorado Profissional em Computação Aplicada (PPCA/UnB)',
      en: 'Professional Doctorate in Applied Computing (PPCA/UnB)',
      es: 'Doctorado Profesional en Computación Aplicada (PPCA/UnB)',
    },
    title: { pt: 'Cibersegurança 1', en: 'Cybersecurity 1', es: 'Ciberseguridad 1' },
    text: {
      pt: 'Cibercrime, ataques cibernéticos, guerra cibernética, fraudes digitais e Cyber Threat Intelligence (CTI), com leitura crítica de artigos, seminários e artigo científico.',
      en: 'Cybercrime, cyberattacks, cyber warfare, digital fraud, and Cyber Threat Intelligence (CTI), with critical paper reading, seminars, and a research article.',
      es: 'Ciberdelito, ciberataques, guerra cibernética, fraudes digitales y Cyber Threat Intelligence (CTI), con lectura crítica de artículos, seminarios y artículo científico.',
    },
    tags: ['Doutorado', 'CTI', 'Guerra Cibernética'],
  },
  {
    id: 'guide-linux',
    categories: ['labs'],
    href: '/guias/linux.html',
    cta: cta.guide,
    meta: { pt: 'Material de apoio • Redes Linux', en: 'Support material • Linux Networks', es: 'Material de apoyo • Redes Linux' },
    title: { pt: 'Linux para Administração de Redes', en: 'Linux for Network Administration', es: 'Linux para Administración de Redes' },
    text: {
      pt: 'Referência rápida de comandos Linux para diagnóstico, configuração, monitoramento e solução de problemas em redes, organizada por tema.',
      en: 'Quick reference of Linux commands for network diagnostics, configuration, monitoring, and troubleshooting, organized by topic.',
      es: 'Referencia rápida de comandos Linux para diagnóstico, configuración, monitoreo y solución de problemas en redes, organizada por tema.',
    },
    tags: ['Linux', 'Shell', 'CLI'],
  },
  {
    id: 'guide-windows',
    categories: ['labs'],
    href: '/guias/windows-redes.html',
    cta: cta.guide,
    meta: { pt: 'Material de apoio • Redes Windows', en: 'Support material • Windows Networks', es: 'Material de apoyo • Redes Windows' },
    title: { pt: 'Windows para Administração de Redes', en: 'Windows for Network Administration', es: 'Windows para Administración de Redes' },
    text: {
      pt: 'Referência rápida de comandos Windows (cmd e PowerShell) para diagnóstico, configuração, monitoramento e solução de problemas em redes, organizada por tema.',
      en: 'Quick reference of Windows commands (cmd and PowerShell) for network diagnostics, configuration, monitoring, and troubleshooting, organized by topic.',
      es: 'Referencia rápida de comandos Windows (cmd y PowerShell) para diagnóstico, configuración, monitoreo y solución de problemas en redes, organizada por tema.',
    },
    tags: ['Windows', 'PowerShell', 'CLI'],
  },
  {
    id: 'sim-router',
    featured: true,
    categories: ['simulators'],
    href: '/simuladores/router_simulator.html',
    cta: cta.sim,
    title: { pt: 'Simulador de Roteador & Protocolos IP', en: 'Router & IP Protocols Simulator', es: 'Simulador de Router y Protocolos IP' },
    text: {
      pt: 'Encaminhamento de pacotes camada 3 e roteamento dinâmico: cabeçalho IPv4, lookup por LPM, decremento de TTL e simulação de OSPF multiárea e RIPv2.',
      en: 'Layer 3 packet forwarding and dynamic routing: IPv4 header, LPM lookup, TTL decrement, and simulation of multi-area OSPF and RIPv2.',
      es: 'Reenvío de paquetes de capa 3 y enrutamiento dinámico: encabezado IPv4, búsqueda LPM, decremento de TTL y simulación de OSPF multiárea y RIPv2.',
    },
    tags: ['OSPF', 'RIPv2', 'LPM'],
  },
  {
    id: 'sim-dhcp',
    categories: ['simulators'],
    href: '/simuladores/dhcp-simulator.html',
    cta: cta.sim,
    title: { pt: 'Simulador de DHCP (DORA)', en: 'DHCP Simulator (DORA)', es: 'Simulador de DHCP (DORA)' },
    text: {
      pt: 'Simulação interativa do DHCP (RFC 2131): Discover, Offer, Request e Acknowledge com gestão de leases e prevenção de conflitos ARP.',
      en: 'Interactive DHCP simulation (RFC 2131): Discover, Offer, Request, and Acknowledge with lease management and ARP conflict prevention.',
      es: 'Simulación interactiva de DHCP (RFC 2131): Discover, Offer, Request y Acknowledge con gestión de leases y prevención de conflictos ARP.',
    },
    tags: ['DHCP', 'RFC 2131', 'ARP'],
  },
  {
    id: 'sim-icmp',
    categories: ['simulators'],
    href: '/simuladores/icmp-simulator.html',
    cta: cta.sim,
    title: { pt: 'Simulador de ICMP (ping e traceroute)', en: 'ICMP Simulator (ping and traceroute)', es: 'Simulador de ICMP (ping y traceroute)' },
    text: {
      pt: 'ping, traceroute, tracert e hping3 em uma rede simulada (RFC 792): Echo, Time Exceeded, Destination Unreachable, fragmentação, PMTUD, ACLs e loops, com captura e hex dump.',
      en: 'ping, traceroute, tracert, and hping3 on a simulated network (RFC 792): Echo, Time Exceeded, Destination Unreachable, fragmentation, PMTUD, ACLs, and loops, with capture and hex dump.',
      es: 'ping, traceroute, tracert y hping3 en una red simulada (RFC 792): Echo, Time Exceeded, Destination Unreachable, fragmentación, PMTUD, ACLs y bucles, con captura y volcado hexadecimal.',
    },
    tags: ['ICMP', 'RFC 792', 'PMTUD'],
  },
];

export const profiles = [
  { id: 'email', icon: '✉', label: 'E-mail', value: 'peotta@gmail.com', href: 'mailto:peotta@gmail.com' },
  { id: 'github', icon: '⌘', label: 'GitHub', value: 'github.com/peotta', href: 'https://github.com/peotta' },
  { id: 'linkedin', icon: 'in', label: 'LinkedIn', value: 'linkedin.com/in/laertepeotta', href: 'https://linkedin.com/in/laertepeotta' },
  { id: 'orcid', icon: '◎', label: 'ORCID', value: '0000-0002-2075-6601', href: 'https://orcid.org/0000-0002-2075-6601' },
  { id: 'lattes', icon: '▣', label: 'Lattes', value: 'lattes.cnpq.br/0746844511320579', href: 'https://lattes.cnpq.br/0746844511320579' },
  { id: 'dblp', icon: '◫', label: 'DBLP', value: 'dblp.org/pid/235/0910', href: 'https://dblp.org/pid/235/0910.html' },
];

export const RAVENS = {
  page: '/guias/ravens.html',
  repo: 'https://github.com/peotta/ravens',
  logo: '/assets/img/ravens-logo.webp',
};

export const SPOTIFY_URL = 'https://open.spotify.com/show/59S06LhFsKlyvfLFQCJ8fK?si=64f2b8a5edcd4c8e';
